loco_translate.settings:
  type: config_object
  label: 'Loco translate settings'
  mapping:
    api:
      type: mapping
      label: 'API'
      mapping:
        fullaccess_key:
          type: string
          label: 'Full Access API Key'
        export_key:
          type: string
          label: 'Export API Key'
    automation:
      type: mapping
      label: 'Automation'
      mapping:
        push:
          type: mapping
          label: 'Push'
          mapping:
            interval:
              type: integer
              label: 'Interval'
            langcodes:
              type: sequence
              label: 'Langcodes'
            template:
              type: string
              label: 'Template'
        pull:
          type: mapping
          label: 'Import'
          mapping:
            interval:
              type: integer
              label: 'Interval'
            langcodes:
              type: sequence
              label: 'Langcodes'
            status:
              type: string
              label: 'Status'
